_wandb:
    value:
        cli_version: 0.23.0
        e:
            jypfloo700cvoqtpimxpgdummed68hpt:
                codePath: /home/victorvj/Documents/Uni/DL/deep_learning_course/assignment1/test.ipynb
                codePathLocal: test.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "133807734784"
                        used: "65449566208"
                email: victor.guldregn@gmail.com
                executable: /bin/python
                git:
                    commit: efae3be4d313d500000e32e0613054078332e167
                    remote: https://github.com/P1N60/deep_learning_course
                host: linus
                memory:
                    total: "7870513152"
                os: Linux-6.16.8-400.asahi.fc42.aarch64+16k-aarch64-with-glibc2.41
                program: /home/victorvj/Documents/Uni/DL/deep_learning_course/assignment1/test.ipynb
                python: CPython 3.13.9
                root: /home/victorvj/Documents/Uni/DL/deep_learning_course/assignment1
                startedAt: "2025-11-27T14:38:29.758959Z"
                writerId: jypfloo700cvoqtpimxpgdummed68hpt
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.13.9
            "5": 0.23.0
            "8":
                - 1
            "12": 0.23.0
            "13": linux-aarch64
architecture:
    value: DynamicXORModel
batch_size:
    value: 64
epochs:
    value: 50
hidden_dim:
    value: 10
hidden_layers:
    value: 3
input_dim:
    value: 2
learning_rate:
    value: 0.01
loss_function:
    value: BCELoss
optimizer:
    value: Adam
output_dim:
    value: 1
